### ISSUE TITLE
Style Things

### ISSUE THREAD

**Issue by hollingerc3** [mjcuva/ASP-Site#2]
Just a little note about controllers:

We should use the controllerAs syntax wherever possible (see the style guide Marc posted). Basically, instead of defining everything on an injected $scope ($scope.property = blah), we capture the context (this) in the controller and bind it straight to that (var vm = this; vm.property = blah). We then only use an injected $scope for the utility it offers ($on, $emit, etc). If that doesn't make sense, lemme know, and check out the style guide.

One way to look at it is we're making the controller into a constructor, rather than binding it all to a $scope. By injecting and binding to the $scope, we're technically calling scope.controller.$scope.property (gross). This changes it to scope.controller.property.

**Comment by mjcuva** [comment]
I think we fixed all of the instances where this wasn't done.
